# solve file for day06 problem 
import sys
from os import path

sys.path.append(path.dirname(path.dirname(path.abspath(__file__))))

from read_file import by_lines

solve_dir = path.dirname(path.abspath(__file__))
input_path = path.join(solve_dir, "input")
content = by_lines(input_path)

# generated by make_dirs.py

def detect_packet(packet_len: int) -> int:
    from collections import defaultdict
    line = content[0]
    counter = defaultdict(int)
    i = 0
    for j, ch in enumerate(line):
        while counter[ch] > 0:
            counter[line[i]] -= 1
            i += 1
        counter[ch] += 1
        if j-i+1 == packet_len:
            return j+1

    raise ValueError("no answer")

def part1() -> int:
    return detect_packet(4)

def part2() -> int:
    return detect_packet(14)

if __name__ == "__main__":
    print("part1", part1())
    print("part2", part2())
