# solve file for day03 problem
import sys
from os import path
sys.path.append(path.dirname(path.dirname(path.abspath(__file__))))

from read_file import by_lines
solve_dir = path.dirname(path.abspath(__file__))
input_path = path.join(solve_dir, "input")
content = by_lines(input_path)

# generated by make_dirs.py

a_z = list(map(chr, range(ord("a"), ord("z")+1)))
A_Z = list(map(chr, range(ord("A"), ord("Z")+1)))
priorities = {ch: (i + 1) for i, ch in enumerate(a_z + A_Z)}


def part1():
    res = 0
    for l in content:
        counterpart = len(l) // 2
        first, second = l[counterpart:], l[:counterpart]

        res += get_priority([first, second])

    print("part1", res)
    

def part2():
    res = 0
    for i in range(0, len(content), 3):
        res += get_priority(content[i:i+3])
    print("part2", res)



from typing import List
def get_priority(groups: List[str]) -> int:
    sets = []
    for g in groups[:-1]:
        sets.append(set(list(g)))
    
    for ch in groups[-1]:
        if all([ch in s for s in sets]):
            return priorities[ch]

    raise ValueError("no same character")


part1()
part2()




